namespace RagEvaluator.Domain.Enums
{
    /// <summary>
    /// Quality of the response generated by the LLM.
    /// </summary>
    public enum ResponseQuality
    {
        CorrectAndComplete = 0,
        VagueOrIncomplete = 1,
        Incorrect = 2,
        Hallucinated = 3
    }
}