name: Rag Evaluator CI

on:
  push: 
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore RagEvaluator.API/RagEvaluator.API.csproj

    - name: Build API
      run: dotnet build RagEvaluator.API/RagEvaluator.API.csproj --no-restore --configuration Release

  backend-test:
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore RagEvaluator.Test/RagEvaluator.Test.csproj

    - name: Build tests
      run: dotnet build RagEvaluator.Test/RagEvaluator.Test.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --project RagEvaluator.Test/RagEvaluator.Test.csproj --no-build --configuration Release --verbosity normal

  ui-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: RagEvaluator.WebUi/package-lock.json

    - name: Install dependencies
      run: |
        cd RagEvaluator.WebUi
        npm ci

    - name: Run linter
      run: |
        cd RagEvaluator.WebUi
        npm run lint

  ui-build:
    runs-on: ubuntu-latest
    needs: ui-lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: RagEvaluator.WebUi/package-lock.json

    - name: Install dependencies
      run: |
        cd RagEvaluator.WebUi
        npm ci

    - name: Build
      run: |
        cd RagEvaluator.WebUi
        npm run build

  ui-test:
    runs-on: ubuntu-latest
    needs: ui-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: RagEvaluator.WebUi/package-lock.json

    - name: Install dependencies
      run: |
        cd RagEvaluator.WebUi
        npm ci

    - name: Run tests
      run: |
        cd RagEvaluator.WebUi
        npm run test -- --run